### ISSUE TITLE
StackedInline 

### ISSUE THREAD

**Issue by urit** [potatolondon/djangae#500] opened 2015-12-02 23:12 UTC
No implementation for StackedInline

**Comment by Kazade** [comment] 2015-12-03 09:11
Do you have any more information? What doesn't work? Do you get an error?

**Comment by urit** [comment] 2015-12-03 10:02
It shows tabular inline instead

**Comment by olasitarska** [comment] 2015-12-03 10:21
Hi Uri!

Thank you for taking the time to report this, but I'm afraid StackedInline or TabularInline problems you're having are not connected to Djangae. If you're sure that they are caused by Djangae, please provide us with the steps and code required to reproduce this bug, as well as screenshots so we can see what exactly is happening. 

I'm gonna close this for now, but please feel free to reopen this when you make sure it's Djangae's fault. 

Thanks!
Ola

**Closed by olasitarska** 2015-12-03 10:21 UTC
