### ISSUE TITLE
Can not runserver with 1.9.51 sdk

### ISSUE THREAD

**Issue by TysonRV** [potatolondon/djangae#883] opened 2017-04-05 16:04 UTC
Hi, 

I have experienced some issues on my project with the latest Djangae build (Supporting AppEngine 1.9.51). 

When I run `./manage.py runserver`, the process dies shortly after, saying it can't connect to the API Server..

I have posted the full stack trace [here](https://pastebin.com/XKMgAY37)

Any help is really appreciated

**Comment by davidwtbuxton** [comment] 2017-04-05 16:33
Hi,

#880 was just merged which is intended to fix this issue.

Can you test with the current head of the master branch and let us know if it works?

Thanks,

David B.

**Comment by TysonRV** [comment] 2017-04-05 16:53
Hi David, 

many thanks for the quick reply. 
I forgot to say that I am already using the current head of the master branch with my project. 

Tirso

**Comment by adamalton** [comment] 2017-04-05 16:56
Just to check the obvious: do you have another `runserver` running in
another terminal?

**Comment by TysonRV** [comment] 2017-04-05 17:05
No, I haven't. We are able to reproduce the same error in more than one laptop.

**Comment by Kazade** [comment] 2017-04-06 15:23
We've just test on a Fedora laptop, and a Macbook with different projects on 1.9.51 and both run OK.  The only explanation I can find is that there is some other process running on 8002, I can see from the logs that there is also another process running on port 8080.

These commands might help you find out what they are:

`sudo lsof -i :8002`
`sudo lsof -i :8080`

**Comment by farridav** [comment] 2017-04-06 15:46
I've noticed that this happens when we use `DJANGAE_ADDITIONAL_MODULES`, with our other module and dispatch.yaml... i think perhaps its trying to bring up an api server for each module ?

**Comment by Kazade** [comment] 2017-04-07 09:18
Right, that's really helpful - I'll have a play around

**Closed** 2017-04-07 15:13 UTC

**Comment by TysonRV** [comment] 2017-04-07 15:48
Thanks guys, much better now =)

**Comment by farridav** [comment] 2017-04-07 15:49
I can confirm that the recent commits on this resolve the issue when using `DJANGAE_ADDITIONAL_MODULES`, I also had another (unreported) related issue with the blobstore port being mixed up which is also inadvertently solved too :) .. thanks @Kazade @adamalton @davidwtbuxton 

Your speedy help on this has really helped me out..

**Comment by adamalton** [comment] 2017-04-07 15:54
👍
