### ISSUE TITLE
ModuleNotFoundError: No module named 'google.appengine'

### ISSUE THREAD

**Issue by interpegasus** [potatolondon/djangae#1198] opened 2020-02-17 15:47 UTC
Hi, I would like to know how to install and run the latest version of djangae. Is there a sample app that can be used as an example?

After following the [installation guide](https://djangae.readthedocs.io/en/latest/installation/) , the error below is returned. Thanks in advance and great work! 

```
$ ./manage.py runserver 0.0.0.0:8080

~/.pyenv/versions/3.7.5/lib/python3.7/site-packages/djangae/contrib/security/middleware.py in <module>
      4 import yaml
      5 
----> 6 from google.appengine.api import urlfetch
      7 
      8 from django.conf import settings
ModuleNotFoundError: No module named 'google.appengine'
```

**wsgi.py**
```
import os

from django.core.wsgi import get_wsgi_application

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'interpegasus.settings')

application = get_wsgi_application()
```

Steps to reproduce

Traceback or other info
* OS: Ubuntu 18.04.3 LTS
* Djangae version: master branch
* Django version: 2.2.10
* App Engine SDK version: 1.9.88
$ gcloud --version
Google Cloud SDK 280.0.0
alpha 2020.02.07
app-engine-go 
app-engine-python 1.9.88
app-engine-python-extras 1.9.88
beta 2020.02.07
bq 2.0.53
cloud-datastore-emulator 2.1.0
core 2020.02.07
gsutil 4.47
kubectl 2020.02.07
* Using Cloud SDK: yes

**Comment by Kazade** [comment] 2020-02-18 16:18
Thanks for the report! This is actually a duplicate of #1196 - hopefully we'll get it fixed soon!

**Comment by Kazade** [comment] 2020-02-18 16:18
For now you can disable the security middleware and it should work :)

**Closed by Kazade** 2020-02-18 16:18 UTC

**Comment by interpegasus** [comment] 2020-02-18 17:12
Thank you it is working fine. Great work!
