### ISSUE TITLE
KeyError on nested prefetching of RelatedSetField

### ISSUE THREAD

**Issue by mvd7793** [potatolondon/djangae#829] opened 2017-02-09 16:51 UTC
Continuing from the fix to #774, there's a bug with nested keys.

```python
# =======  Models  ======= 
class Post(models.Model):
    content = models.TextField()
    authors = fields.RelatedSetField('Author', related_name='posts')

class Author(models.Model):
    name = fields.CharField()
    awards = fields.RelatedSetField('Awards')
    
class Awards(models.Model):
    name = fields.CharField()
    
# =======  Usage  ======= 
# Causes a KeyError
posts = Post.objects.all().prefetch_related('authors__awards')
```

This happens because the values being read from the nested field come back as long, which does not match what's in `matchers` in #808. Fix incoming in a PR.

**Comment by Kazade** [comment] 2017-03-13 11:11
I've written a test locally for this, and it seems to pass. I think the problem you were actually seeing is the one fixed in #851 where the underlying IDs weren't coerced to integers upon saving (so for example `awards_ids` may be a list of strings). If your test data came from POST data that's probably the cause.

If that is the case, you should probably resave your instances after pinning to a later Djangae commit (after #851 fix was merged).

**Closed** 2017-03-13 12:58 UTC
