### ISSUE TITLE
Remote shell lines messes up when using left/right arrows and inserting/deleting characters

### ISSUE THREAD

**Issue by jacobg** [potatolondon/djangae#517] opened 2015-12-16 00:12 UTC

**Comment by jacobg** [comment] 2015-12-16 12:42
Oh also, the display of multi-line statements doesn't look great:

```
(remote) my-app >>> for i in range(5):
...    print('Howdy!')
... 
Howdy!
Howdy!
Howdy!
Howdy!
Howdy!
(remote) my-app >>> 
```

**Comment by adamalton** [comment] 2016-06-17 14:59
This is a limitation caused by App Engine.  See: https://code.google.com/p/googleappengine/issues/detail?id=7541.

I'm going to close this as it falls into the GAE camp rather than the Djangae camp.

**Closed by adamalton** 2016-06-17 14:59 UTC
