### ISSUE TITLE
DeleteCommand does not use pre-fetched results

### ISSUE THREAD

**Issue by jacobg** [potatolondon/djangae#496] opened 2015-12-01 16:55 UTC
Suppose I build a queryset of items that I want to delete. But before I delete them, I want to gather some information from them. And then I want to delete them, e.g.,
```python
queryset = MYMODEL.objects.filter(<some filters>)
for o in queryset:
  do_some_read_operation(o)
queryset.delete()
```
I would expect that delete would take advantage of the fact that the results have already been fetched, and simply do the constraint check, and finally delete the keys in one bulk operation.

But in reality, DeleteCommand re-fetches all the items before proceeding.

So what it should do is re-use the already-fetched entities.

**Comment by Kazade** [comment] 2016-03-10 12:09
Hi @jacobg 

In an ideal world that's what we'd do, but unfortunately it's not quite so simple :(

The problem is that Django doesn't give us access to those fetched objects which are stored on the `Queryset`. The datastore backend works like any other backend and only has access to the `Query`, and this query is the result of Django running the deletion collector (to gather related objects) which may send multiple queries.

But, even if we did have access to that set of objects, it's possible that some of them could have changed in another request between the queryset fetch, and the `delete()` call - this introduces a few distinct issues:

- Objects might be deleted which no longer match the query (not a problem on SQL, a problem for us though)
- If you are using unique constraints, those constraints should be freed and for that to happen we'd need to refetch the entity to make sure the unique values were up to date
- If you are using concrete model inheritance (which uses polymodels in the datastore) you might not need to even delete those entities, but instead update them

The good news is that as part of the Django 1.9 support which was just merged we have rewritten deletion to be more efficient, it uses `DeleteAsync` and `PutAsync` and transactionally deletes thing in batches of 25. According to the App Engine docs, many smaller RPC calls are faster than one large one so this is probably as fast as we're going to get it without some serious profiling!

**Closed by Kazade** 2016-03-10 12:09 UTC
